"""
test_data_loading.py
--------------------
Tests for data loading functions.
Uses synthetic in-memory data; does not require actual competition files.
"""

import io
import pytest
import pandas as pd

from src.data import load_train, load_test, get_texts_and_labels, get_test_texts
from src.constants import TRAIN_TEXT_COL, TRAIN_LABEL_COL, TEST_TEXT_COL


# ── Fixtures ──────────────────────────────────────────────────────────────────

def make_train_csv(rows=None) -> str:
    """Return a valid train CSV string using actual column names (TEXT, LABEL)."""
    if rows is None:
        rows = [
            ("Hello world, this is human text.", 0),
            ("This response was generated by DeepSeek.", 1),
            ("Grok said something interesting here.", 2),
            ("Claude crafted this sentence.", 3),
            ("Gemini produced this paragraph.", 4),
            ("ChatGPT output this text.", 5),
        ]
    lines = [f"{TRAIN_TEXT_COL},{TRAIN_LABEL_COL}"]
    for text, label in rows:
        lines.append(f'"{text}",{label}')
    return "\n".join(lines)


def make_test_csv(rows=None) -> str:
    """Return a valid test CSV string using actual column name (TEXT)."""
    if rows is None:
        rows = [
            "Some test text here.",
            "Another test sentence.",
            "Third test sample.",
        ]
    lines = [TEST_TEXT_COL]
    for text in rows:
        lines.append(f'"{text}"')
    return "\n".join(lines)


# ── Data loading tests ────────────────────────────────────────────────────────

def test_load_train_returns_dataframe(tmp_path):
    """load_train should return a DataFrame with the correct columns."""
    csv_content = make_train_csv()
    csv_file = tmp_path / "train.csv"
    csv_file.write_text(csv_content, encoding="utf-8")

    df = load_train(str(csv_file))
    assert isinstance(df, pd.DataFrame)
    assert TRAIN_TEXT_COL in df.columns
    assert TRAIN_LABEL_COL in df.columns


def test_load_train_correct_row_count(tmp_path):
    """load_train should return all non-null rows."""
    csv_content = make_train_csv()
    csv_file = tmp_path / "train.csv"
    csv_file.write_text(csv_content, encoding="utf-8")

    df = load_train(str(csv_file))
    assert len(df) == 6


def test_load_train_label_dtype_is_int(tmp_path):
    """Labels should be coerced to int."""
    csv_content = make_train_csv()
    csv_file = tmp_path / "train.csv"
    csv_file.write_text(csv_content, encoding="utf-8")

    df = load_train(str(csv_file))
    assert df[TRAIN_LABEL_COL].dtype == int


def test_load_test_returns_dataframe(tmp_path):
    """load_test should return a DataFrame with text column."""
    csv_content = make_test_csv()
    csv_file = tmp_path / "test.csv"
    csv_file.write_text(csv_content, encoding="utf-8")

    df = load_test(str(csv_file))
    assert isinstance(df, pd.DataFrame)
    assert TEST_TEXT_COL in df.columns
    assert len(df) == 3


def test_get_texts_and_labels(tmp_path):
    """get_texts_and_labels should return (list, np.array)."""
    import numpy as np
    csv_content = make_train_csv()
    csv_file = tmp_path / "train.csv"
    csv_file.write_text(csv_content, encoding="utf-8")

    df = load_train(str(csv_file))
    X, y = get_texts_and_labels(df)

    assert isinstance(X, list)
    assert isinstance(y, np.ndarray)
    assert len(X) == len(y) == 6


def test_get_test_texts(tmp_path):
    """get_test_texts should return a list of strings."""
    csv_content = make_test_csv()
    csv_file = tmp_path / "test.csv"
    csv_file.write_text(csv_content, encoding="utf-8")

    df = load_test(str(csv_file))
    texts = get_test_texts(df)

    assert isinstance(texts, list)
    assert all(isinstance(t, str) for t in texts)
    assert len(texts) == 3


def test_load_train_drops_null_rows(tmp_path):
    """Rows with null text or label should be silently dropped."""
    csv_content = (
        f"{TRAIN_TEXT_COL},{TRAIN_LABEL_COL}\n"
        '"Good text",0\n'
        ',1\n'                  # null text
        '"Another text",\n'    # null label
        '"Valid text",2\n'
    )
    csv_file = tmp_path / "train.csv"
    csv_file.write_text(csv_content, encoding="utf-8")

    df = load_train(str(csv_file))
    assert len(df) == 2  # Only two valid rows


def test_load_train_file_not_found():
    """load_train should raise FileNotFoundError for missing files."""
    with pytest.raises(FileNotFoundError):
        load_train("/nonexistent/path/train.csv")


def test_load_test_file_not_found():
    """load_test should raise FileNotFoundError for missing files."""
    with pytest.raises(FileNotFoundError):
        load_test("/nonexistent/path/test.csv")
